import { Job } from "@/lib/types/job";

export const data: Job[] = [
  {
    companyLogo: "/assets/job/Appstore.png",
    position: "Software Engineer",
    type: "InternShip",
    id: 1,
    jobRole: "Development and Maintenance of Web Applications",
    experience: "3-5 years",
    minimumQualification:
      "Bachelor's Degree in Computer Science or related field",
    location: "New York, NY",
    experienceLevel: "Mid-level",
    applyLink: "www.google.com",
    requirements: [
      "Proven experience as a Software Engineer or similar role",
      "Familiarity with Agile development methodologies",
      "Experience with software design and development in a test-driven environment",
      "Knowledge of coding languages (e.g., C++, Java, JavaScript) and frameworks/systems (e.g., AngularJS, Git)",
      "Experience with databases and Object-Relational Mapping (ORM) frameworks",
      "Ability to learn new languages and technologies",
      "Excellent communication skills",
      "Resourcefulness and troubleshooting aptitude",
      "Attention to detail",
    ],
    responsibilities: [
      "Execute full software development life cycle (SDLC)",
      "Develop flowcharts, layouts and documentation to identify requirements and solutions",
      "Write well-designed, testable code",
      "Produce specifications and determine operational feasibility",
      "Integrate software components into a fully functional software system",
      "Develop software verification plans and quality assurance procedures",
      "Document and maintain software functionality",
      "Troubleshoot, debug and upgrade existing systems",
      "Deploy programs and evaluate user feedback",
      "Comply with project plans and industry standards",
    ],
  },
  {
    companyLogo: "/assets/job/Appstore.png",
    id: 2,
    position: "Marketing Manager",
    type: "InternShip",
    jobRole: "Planning and executing marketing strategies",
    experience: "5-7 years",
    applyLink: "www.google.com",
    minimumQualification:
      "Bachelor's Degree in Marketing, Business Administration, or related field",
    location: "San Francisco, CA",
    experienceLevel: "Senior-level",
    requirements: [
      "Proven experience as a Marketing Manager or similar role",
      "Experience in digital and print marketing, content marketing, and social media marketing",
      "Strong project management, multitasking, and decision-making skills",
      "Metrics-driven marketing mind with eye for creativity",
      "Experience with marketing automation and CRM tools",
      "Excellent communication and leadership skills",
      "Analytical mind and good problem-solving skills",
    ],
    responsibilities: [
      "Develop strategies and tactics to get the word out about our company and drive qualified traffic",
      "Deploy successful marketing campaigns and own their implementation from ideation to execution",
      "Experiment with a variety of organic and paid acquisition channels",
      "Produce valuable and engaging content for our website and blog that attracts and converts our target groups",
      "Build strategic relationships and partner with key industry players, agencies and vendors",
      "Prepare and monitor the marketing budget on a quarterly and annual basis and allocate funds wisely",
      "Oversee and approve marketing material, from website banners to hard copy brochures and case studies",
      "Measure and report on the performance of marketing campaigns, gain insight and assess against goals",
    ],
  },
  {
    companyLogo: "/assets/job/Appstore.png",
    id: 3,
    position: "Project Manager",
    type: "Full Time",
    jobRole: "Managing projects from inception to completion",
    experience: "4-6 years",
    applyLink: "https://www.youtube.com/watch?v=4IhF5oh7QGs",
    minimumQualification:
      "Bachelor's Degree in Project Management, Business, or related field",
    location: "Austin, TX",
    experienceLevel: "Mid-level",
    requirements: [
      "Proven experience as a Project Manager or similar role",
      "Excellent organizational and leadership skills",
      "Experience in project management software (e.g., MS Project)",
      "Ability to manage multiple projects simultaneously",
      "Strong problem-solving skills",
      "Excellent communication and teamwork skills",
      "PMP or PRINCE2 certification is a plus",
    ],
    responsibilities: [
      "Coordinate internal resources and third parties/vendors for the flawless execution of projects",
      "Ensure that all projects are delivered on-time, within scope and within budget",
      "Develop project scopes and objectives, involving all relevant stakeholders",
      "Ensure resource availability and allocation",
      "Develop a detailed project plan to monitor and track progress",
      "Manage changes to the project scope, project schedule and project costs",
      "Measure project performance using appropriate tools and techniques",
      "Perform risk management to minimize project risks",
      "Create and maintain comprehensive project documentation",
    ],
  },
  {
    companyLogo: "/assets/job/Appstore.png",
    position: "Graphic Designer",
    id: 4,

    type: "Full Time",
    jobRole: "Creating visual content to communicate messages",
    experience: "2-4 years",
    applyLink: "www.google.com",
    minimumQualification:
      "Bachelor's Degree in Graphic Design or related field",
    location: "Los Angeles, CA",
    experienceLevel: "Mid-level",
    requirements: [
      "Proven graphic designing experience",
      "A strong portfolio of illustrations or other graphics",
      "Familiarity with design software and technologies (such as InDesign, Illustrator, Dreamweaver, Photoshop)",
      "A keen eye for aesthetics and details",
      "Excellent communication skills",
      "Ability to work methodically and meet deadlines",
      "Degree in Design, Fine Arts or related field is a plus",
    ],
    responsibilities: [
      "Study design briefs and determine requirements",
      "Schedule projects and define budget constraints",
      "Conceptualize visuals based on requirements",
      "Prepare rough drafts and present ideas",
      "Develop illustrations, logos and other designs using software or by hand",
      "Use the appropriate colors and layouts for each graphic",
      "Work with copywriters and creative director to produce final design",
      "Test graphics across various media",
      "Amend designs after feedback",
      "Ensure final graphics and layouts are visually appealing and on-brand",
    ],
  },
  {
    companyLogo: "/assets/job/Appstore.png",
    id: 5,

    position: "Data Scientist",
    type: "Full Time",
    jobRole: "Analyzing and interpreting complex data",
    experience: "3-5 years",
    applyLink: "www.google.com",
    minimumQualification:
      "Bachelor's Degree in Data Science, Statistics, Computer Science, or related field",
    location: "Seattle, WA",
    experienceLevel: "Mid-level",
    requirements: [
      "Experience in data mining",
      "Understanding of machine-learning and operations research",
      "Knowledge of R, SQL and Python; familiarity with Scala, Java or C++ is an asset",
      "Experience using business intelligence tools (e.g., Tableau) and data frameworks (e.g., Hadoop)",
      "Analytical mind and business acumen",
      "Strong math skills (e.g., statistics, algebra)",
      "Problem-solving aptitude",
      "Excellent communication and presentation skills",
    ],
    responsibilities: [
      "Identify valuable data sources and automate collection processes",
      "Undertake preprocessing of structured and unstructured data",
      "Analyze large amounts of information to discover trends and patterns",
      "Build predictive models and machine-learning algorithms",
      "Combine models through ensemble modeling",
      "Present information using data visualization techniques",
      "Propose solutions and strategies to business challenges",
      "Collaborate with engineering and product development teams",
    ],
  },
  {
    companyLogo: "/assets/job/Appstore.png",
    position: "Software Engineer",
    id: 6,

    type: "InternShip",
    jobRole: "Development and Maintenance of Web Applications",
    experience: "3-5 years",
    minimumQualification:
      "Bachelor's Degree in Computer Science or related field",
    location: "New York, NY",
    experienceLevel: "Mid-level",
    applyLink: "www.google.com",
    requirements: [
      "Proven experience as a Software Engineer or similar role",
      "Familiarity with Agile development methodologies",
      "Experience with software design and development in a test-driven environment",
      "Knowledge of coding languages (e.g., C++, Java, JavaScript) and frameworks/systems (e.g., AngularJS, Git)",
      "Experience with databases and Object-Relational Mapping (ORM) frameworks",
      "Ability to learn new languages and technologies",
      "Excellent communication skills",
      "Resourcefulness and troubleshooting aptitude",
      "Attention to detail",
    ],
    responsibilities: [
      "Execute full software development life cycle (SDLC)",
      "Develop flowcharts, layouts and documentation to identify requirements and solutions",
      "Write well-designed, testable code",
      "Produce specifications and determine operational feasibility",
      "Integrate software components into a fully functional software system",
      "Develop software verification plans and quality assurance procedures",
      "Document and maintain software functionality",
      "Troubleshoot, debug and upgrade existing systems",
      "Deploy programs and evaluate user feedback",
      "Comply with project plans and industry standards",
    ],
  },
];
